import { ModuleDefinition, ModuleCategory } from '@/types/builder';
import { getCustomModules } from '@/lib/speckle/customModules';

export const MODULE_CATALOG: ModuleDefinition[] = [
  // ===== STRUCTURAL (구조 모듈) =====
  {
    id: 'exterior-wall',
    name: 'Exterior Wall',
    nameKo: '외벽',
    category: 'STRUCTURAL',
    description: '건물 외부 벽체',
    width: 3.6,
    depth: 0.3,
    height: 3.0,
    gridWidth: 6,
    gridDepth: 1,
    gridHeight: 5,
    basePrice: 2_400_000,
    color: '#8B7355',
  },
  {
    id: 'interior-wall',
    name: 'Interior Wall',
    nameKo: '내벽',
    category: 'STRUCTURAL',
    description: '실내 칸막이 벽체',
    width: 3.6,
    depth: 0.15,
    height: 3.0,
    gridWidth: 6,
    gridDepth: 1,
    gridHeight: 5,
    basePrice: 1_200_000,
    color: '#F5F5DC',
  },
  {
    id: 'floor-slab',
    name: 'Floor Slab',
    nameKo: '바닥슬래브',
    category: 'STRUCTURAL',
    description: '바닥/층간 슬래브',
    width: 3.6,
    depth: 3.6,
    height: 0.3,
    gridWidth: 6,
    gridDepth: 6,
    gridHeight: 1,
    basePrice: 3_600_000,
    color: '#A0A0A0',
  },
  {
    id: 'flat-roof',
    name: 'Flat Roof',
    nameKo: '평지붕',
    category: 'STRUCTURAL',
    description: '평탄 지붕 슬래브',
    width: 3.6,
    depth: 3.6,
    height: 0.3,
    gridWidth: 6,
    gridDepth: 6,
    gridHeight: 1,
    basePrice: 4_200_000,
    color: '#708090',
  },
  {
    id: 'column',
    name: 'Column',
    nameKo: '기둥',
    category: 'STRUCTURAL',
    description: '수직 지지 기둥',
    width: 0.6,
    depth: 0.6,
    height: 3.0,
    gridWidth: 1,
    gridDepth: 1,
    gridHeight: 5,
    basePrice: 800_000,
    color: '#696969',
  },

  // ===== FUNCTIONAL (기능 모듈) =====
  {
    id: 'kitchen',
    name: 'Kitchen',
    nameKo: '주방',
    category: 'FUNCTIONAL',
    description: '주방 유닛 (싱크대, 조리대 포함)',
    width: 3.6,
    depth: 3.6,
    height: 3.0,
    gridWidth: 6,
    gridDepth: 6,
    gridHeight: 5,
    basePrice: 18_000_000,
    color: '#DEB887',
  },
  {
    id: 'bathroom',
    name: 'Bathroom',
    nameKo: '욕실',
    category: 'FUNCTIONAL',
    description: '욕실 유닛 (위생기구 포함)',
    width: 2.4,
    depth: 2.4,
    height: 3.0,
    gridWidth: 4,
    gridDepth: 4,
    gridHeight: 5,
    basePrice: 12_000_000,
    color: '#B0E0E6',
  },
  {
    id: 'bedroom',
    name: 'Bedroom',
    nameKo: '침실',
    category: 'FUNCTIONAL',
    description: '침실 공간',
    width: 3.6,
    depth: 4.2,
    height: 3.0,
    gridWidth: 6,
    gridDepth: 7,
    gridHeight: 5,
    basePrice: 15_000_000,
    color: '#E6D5B8',
  },
  {
    id: 'living-room',
    name: 'Living Room',
    nameKo: '거실',
    category: 'FUNCTIONAL',
    description: '거실 공간',
    width: 4.8,
    depth: 4.2,
    height: 3.0,
    gridWidth: 8,
    gridDepth: 7,
    gridHeight: 5,
    basePrice: 20_000_000,
    color: '#F5DEB3',
  },
  {
    id: 'entrance',
    name: 'Entrance',
    nameKo: '현관',
    category: 'FUNCTIONAL',
    description: '현관 공간',
    width: 1.8,
    depth: 1.8,
    height: 3.0,
    gridWidth: 3,
    gridDepth: 3,
    gridHeight: 5,
    basePrice: 5_000_000,
    color: '#D2B48C',
  },
  {
    id: 'staircase',
    name: 'Staircase',
    nameKo: '계단',
    category: 'FUNCTIONAL',
    description: '층간 연결 계단',
    width: 1.8,
    depth: 3.6,
    height: 3.0,
    gridWidth: 3,
    gridDepth: 6,
    gridHeight: 5,
    basePrice: 8_000_000,
    color: '#A9A9A9',
  },

  // ===== DESIGN (디자인 모듈) =====
  {
    id: 'large-window',
    name: 'Large Window',
    nameKo: '대형창',
    category: 'DESIGN',
    description: '대형 유리창',
    width: 2.4,
    depth: 0.15,
    height: 2.1,
    gridWidth: 4,
    gridDepth: 1,
    gridHeight: 4,
    basePrice: 3_000_000,
    color: '#87CEEB',
  },
  {
    id: 'small-window',
    name: 'Small Window',
    nameKo: '소형창',
    category: 'DESIGN',
    description: '소형 유리창',
    width: 1.2,
    depth: 0.15,
    height: 1.2,
    gridWidth: 2,
    gridDepth: 1,
    gridHeight: 2,
    basePrice: 1_200_000,
    color: '#ADD8E6',
  },
  {
    id: 'balcony',
    name: 'Balcony',
    nameKo: '발코니',
    category: 'DESIGN',
    description: '외부 발코니',
    width: 3.6,
    depth: 1.8,
    height: 1.2,
    gridWidth: 6,
    gridDepth: 3,
    gridHeight: 2,
    basePrice: 6_000_000,
    color: '#C0C0C0',
  },
  {
    id: 'entrance-door',
    name: 'Entrance Door',
    nameKo: '현관도어',
    category: 'DESIGN',
    description: '현관 출입문',
    width: 1.2,
    depth: 0.15,
    height: 2.4,
    gridWidth: 2,
    gridDepth: 1,
    gridHeight: 4,
    basePrice: 2_000_000,
    color: '#8B4513',
  },
];

export const MODULES_BY_CATEGORY: Record<ModuleCategory, ModuleDefinition[]> = {
  STRUCTURAL: MODULE_CATALOG.filter((m) => m.category === 'STRUCTURAL'),
  FUNCTIONAL: MODULE_CATALOG.filter((m) => m.category === 'FUNCTIONAL'),
  DESIGN: MODULE_CATALOG.filter((m) => m.category === 'DESIGN'),
};

export function getModuleById(id: string): ModuleDefinition | undefined {
  // 정적 카탈로그에서 먼저 검색
  const found = MODULE_CATALOG.find((m) => m.id === id);
  if (found) return found;

  // Speckle 커스텀 모듈에서 검색
  return getCustomModules().find((m) => m.id === id);
}
