export type ZoneType =
  | 'ZONE_R1_EXCLUSIVE' | 'ZONE_R2_EXCLUSIVE'
  | 'ZONE_R1_GENERAL' | 'ZONE_R2_GENERAL' | 'ZONE_R3_GENERAL'
  | 'ZONE_R_SEMI'
  | 'ZONE_C_CENTRAL' | 'ZONE_C_GENERAL' | 'ZONE_C_NEIGHBORHOOD' | 'ZONE_C_DISTRIBUTION'
  | 'ZONE_I_EXCLUSIVE' | 'ZONE_I_GENERAL' | 'ZONE_I_SEMI'
  | 'ZONE_G_CONSERVATION' | 'ZONE_G_PRODUCTION' | 'ZONE_G_NATURAL'
  | 'ZONE_M_CONSERVATION' | 'ZONE_M_PRODUCTION' | 'ZONE_M_PLANNED'
  | 'ZONE_AGRICULTURE';

export interface ZoneRegulation {
  nameKo: string;
  maxCoverageRatio: number;
  maxFloorAreaRatio: number;
  maxHeight: number;
  maxFloors: number;
  setbackFront: number;
  setbackRear: number;
  setbackLeft: number;
  setbackRight: number;
}

export const ZONE_REGULATIONS: Record<ZoneType, ZoneRegulation> = {
  ZONE_R1_EXCLUSIVE: {
    nameKo: '제1종전용주거지역',
    maxCoverageRatio: 50,
    maxFloorAreaRatio: 100,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 3,
    setbackRear: 2,
    setbackLeft: 1,
    setbackRight: 1,
  },
  ZONE_R2_EXCLUSIVE: {
    nameKo: '제2종전용주거지역',
    maxCoverageRatio: 50,
    maxFloorAreaRatio: 150,
    maxHeight: 12,
    maxFloors: 3,
    setbackFront: 3,
    setbackRear: 2,
    setbackLeft: 1,
    setbackRight: 1,
  },
  ZONE_R1_GENERAL: {
    nameKo: '제1종일반주거지역',
    maxCoverageRatio: 60,
    maxFloorAreaRatio: 200,
    maxHeight: 15,
    maxFloors: 4,
    setbackFront: 2,
    setbackRear: 1.5,
    setbackLeft: 0.5,
    setbackRight: 0.5,
  },
  ZONE_R2_GENERAL: {
    nameKo: '제2종일반주거지역',
    maxCoverageRatio: 60,
    maxFloorAreaRatio: 250,
    maxHeight: 21,
    maxFloors: 7,
    setbackFront: 2,
    setbackRear: 1.5,
    setbackLeft: 0.5,
    setbackRight: 0.5,
  },
  ZONE_R3_GENERAL: {
    nameKo: '제3종일반주거지역',
    maxCoverageRatio: 50,
    maxFloorAreaRatio: 300,
    maxHeight: 30,
    maxFloors: 10,
    setbackFront: 2,
    setbackRear: 1.5,
    setbackLeft: 0.5,
    setbackRight: 0.5,
  },
  ZONE_R_SEMI: {
    nameKo: '준주거지역',
    maxCoverageRatio: 70,
    maxFloorAreaRatio: 500,
    maxHeight: 45,
    maxFloors: 15,
    setbackFront: 2,
    setbackRear: 1,
    setbackLeft: 0.5,
    setbackRight: 0.5,
  },
  ZONE_C_CENTRAL: {
    nameKo: '중심상업지역',
    maxCoverageRatio: 90,
    maxFloorAreaRatio: 1500,
    maxHeight: 0,
    maxFloors: 50,
    setbackFront: 0,
    setbackRear: 0,
    setbackLeft: 0,
    setbackRight: 0,
  },
  ZONE_C_GENERAL: {
    nameKo: '일반상업지역',
    maxCoverageRatio: 80,
    maxFloorAreaRatio: 1300,
    maxHeight: 0,
    maxFloors: 40,
    setbackFront: 1,
    setbackRear: 0,
    setbackLeft: 0,
    setbackRight: 0,
  },
  ZONE_C_NEIGHBORHOOD: {
    nameKo: '근린상업지역',
    maxCoverageRatio: 70,
    maxFloorAreaRatio: 900,
    maxHeight: 0,
    maxFloors: 25,
    setbackFront: 1,
    setbackRear: 0,
    setbackLeft: 0,
    setbackRight: 0,
  },
  ZONE_C_DISTRIBUTION: {
    nameKo: '유통상업지역',
    maxCoverageRatio: 80,
    maxFloorAreaRatio: 1100,
    maxHeight: 0,
    maxFloors: 30,
    setbackFront: 1,
    setbackRear: 0,
    setbackLeft: 0,
    setbackRight: 0,
  },
  ZONE_I_EXCLUSIVE: {
    nameKo: '전용공업지역',
    maxCoverageRatio: 70,
    maxFloorAreaRatio: 300,
    maxHeight: 0,
    maxFloors: 0,
    setbackFront: 3,
    setbackRear: 2,
    setbackLeft: 1,
    setbackRight: 1,
  },
  ZONE_I_GENERAL: {
    nameKo: '일반공업지역',
    maxCoverageRatio: 70,
    maxFloorAreaRatio: 350,
    maxHeight: 0,
    maxFloors: 0,
    setbackFront: 2,
    setbackRear: 1.5,
    setbackLeft: 1,
    setbackRight: 1,
  },
  ZONE_I_SEMI: {
    nameKo: '준공업지역',
    maxCoverageRatio: 70,
    maxFloorAreaRatio: 400,
    maxHeight: 0,
    maxFloors: 0,
    setbackFront: 2,
    setbackRear: 1,
    setbackLeft: 0.5,
    setbackRight: 0.5,
  },
  ZONE_G_CONSERVATION: {
    nameKo: '보전녹지지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 80,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
  ZONE_G_PRODUCTION: {
    nameKo: '생산녹지지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 100,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
  ZONE_G_NATURAL: {
    nameKo: '자연녹지지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 100,
    maxHeight: 10,
    maxFloors: 3,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
  ZONE_M_CONSERVATION: {
    nameKo: '보전관리지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 80,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
  ZONE_M_PRODUCTION: {
    nameKo: '생산관리지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 100,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
  ZONE_M_PLANNED: {
    nameKo: '계획관리지역',
    maxCoverageRatio: 40,
    maxFloorAreaRatio: 100,
    maxHeight: 15,
    maxFloors: 3,
    setbackFront: 3,
    setbackRear: 2,
    setbackLeft: 1,
    setbackRight: 1,
  },
  ZONE_AGRICULTURE: {
    nameKo: '농림지역',
    maxCoverageRatio: 20,
    maxFloorAreaRatio: 80,
    maxHeight: 10,
    maxFloors: 2,
    setbackFront: 5,
    setbackRear: 3,
    setbackLeft: 2,
    setbackRight: 2,
  },
};
